<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_One Piece 100</name>
   <tag></tag>
   <elementGuidId>a131203c-1f9c-44e4-a0b5-25572b6e9e64</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cart-left']/div[2]/div/div[2]/gm-cart-summary/div/div/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.title-product</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5b8bac8c-feb1-4706-ae4e-4570d501a426</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>title-product</value>
      <webElementGuid>06b3775d-33d2-49b2-9e90-d0d3cafc61b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/products/one-piece-100</value>
      <webElementGuid>a8da2be9-1e24-4951-9da0-98aafac18ab3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> One Piece 100 </value>
      <webElementGuid>b26ad821-c4f5-4af7-be59-347805727ff4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cart-left&quot;)/div[@class=&quot;list-cart-summary ng-star-inserted&quot;]/div[@class=&quot;wrap-list&quot;]/div[@class=&quot;cart-item ng-star-inserted&quot;]/gm-cart-summary[@class=&quot;cart-summary&quot;]/div[@class=&quot;wrap-summary&quot;]/div[@class=&quot;img-description&quot;]/div[@class=&quot;div-description&quot;]/a[@class=&quot;title-product&quot;]</value>
      <webElementGuid>02ee448f-cae7-4588-92b5-972f47ecb5d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cart-left']/div[2]/div/div[2]/gm-cart-summary/div/div/div/a</value>
      <webElementGuid>50b18c14-3d30-45a7-8c92-fecae2529b21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'One Piece 100')]</value>
      <webElementGuid>568882c2-f39c-43db-aec8-7c07c505aff4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Matraman'])[1]/following::a[1]</value>
      <webElementGuid>835a7afe-a2ac-4ca4-b290-1775dc9eb3ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gramedia Official -'])[1]/following::a[1]</value>
      <webElementGuid>722e173e-9a6b-4595-9a54-5b31593f3896</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Soft Cover -'])[1]/preceding::a[1]</value>
      <webElementGuid>21e36a28-9b76-4016-8e3f-8a62678f246e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(0.14 kg)'])[1]/preceding::a[1]</value>
      <webElementGuid>b1898d4b-bb55-4bbd-8a0b-59a87810fd79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='One Piece 100']/parent::*</value>
      <webElementGuid>ef408bee-ba2b-4847-a729-ee98f10f9d26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/products/one-piece-100')]</value>
      <webElementGuid>70cb9231-4575-4996-9cf0-38639eab71ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//gm-cart-summary/div/div/div/a</value>
      <webElementGuid>bcdbdeec-815e-4aea-945d-395fadda4a61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/products/one-piece-100' and (text() = ' One Piece 100 ' or . = ' One Piece 100 ')]</value>
      <webElementGuid>e1e4ae4d-d65c-4d1e-8f82-f6609fe8988c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
