<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Lihat Tas Belanja</name>
   <tag></tag>
   <elementGuidId>f749b324-12de-4ae7-9f21-df97699dcd39</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.continue-shopping</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Lihat Tas Belanja' or . = 'Lihat Tas Belanja')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-dialog-container[@id='mat-dialog-2']/gm-add-to-cart-notif/div/div/div[2]/div[2]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f5ef97b2-e6f9-4e02-bd51-d4869292f51d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>continue-shopping</value>
      <webElementGuid>c4ff7378-118e-401d-9477-be247936d378</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lihat Tas Belanja</value>
      <webElementGuid>10251bd5-509e-4f94-b2b7-a644cf3a6dc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-dialog-2&quot;)/gm-add-to-cart-notif[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;modal&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;action&quot;]/button[@class=&quot;continue-shopping&quot;]</value>
      <webElementGuid>f2247913-146d-48af-97c7-29eaa076117f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-2']/gm-add-to-cart-notif/div/div/div[2]/div[2]/button</value>
      <webElementGuid>9972df0a-bc56-426f-a63c-fdc590fc839c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jakarta Timur'])[2]/following::button[1]</value>
      <webElementGuid>5a04ac18-c0f1-4963-a1dd-1ee6d8291fed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Matraman'])[2]/following::button[1]</value>
      <webElementGuid>2070a02e-f1f3-4728-8bcb-586f39a888aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lanjut ke Pembayaran'])[1]/preceding::button[1]</value>
      <webElementGuid>96214e63-b49f-48c5-9c28-cb3edb691a01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rekomendasi untukmu'])[4]/preceding::button[2]</value>
      <webElementGuid>c338d6ae-5610-4f71-aabb-13cf497dfd22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Lihat Tas Belanja']/parent::*</value>
      <webElementGuid>3df2e098-f508-4db3-ab64-b9d1ab193736</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/button</value>
      <webElementGuid>dd875d69-5b4a-4bbb-9d59-85026f735a34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Lihat Tas Belanja' or . = 'Lihat Tas Belanja')]</value>
      <webElementGuid>2b48f29b-8311-46c0-b533-4fb838db9192</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
