<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_store</name>
   <tag></tag>
   <elementGuidId>091afe24-185d-4a4d-8450-39f1cc2f4245</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='warehouse']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#warehouse</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2a5ff7c8-9e54-4897-b8de-7e0ad9012a3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>search-list ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>70d55903-63ad-49fa-9a52-5296b80f9d57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>warehouse</value>
      <webElementGuid>9819f494-f156-48eb-9862-cdbc01b39a4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>warehouse</value>
      <webElementGuid>bc88cf01-914d-4064-b791-ad847b2e602f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Cari Lokasi Warehouse</value>
      <webElementGuid>79959420-0f7a-4929-ab8a-97f10b9c54fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3178c15b-8e11-47ef-8d09-ec04a0831090</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;warehouse&quot;)</value>
      <webElementGuid>478755d4-9e39-463b-a28f-1c0348358797</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='warehouse']</value>
      <webElementGuid>c03bc1c0-1b87-491d-88a6-1094d77f0b8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-0']/gm-product-view-format-store/div/div/div/div/div/input</value>
      <webElementGuid>b9dd939f-7979-4c1f-91a9-25e6e79fb3b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/input</value>
      <webElementGuid>3f414310-6f72-4330-90b5-1c94863d6fb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'warehouse' and @name = 'warehouse' and @placeholder = 'Cari Lokasi Warehouse' and @type = 'text']</value>
      <webElementGuid>093cb1da-493b-4600-8930-2055ff04baf2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
